### ISSUE TITLE
Proposal to allow get_contents() to be non recursive

### ISSUE THREAD

**Issue by Moult** [lfparis/forge-python-wrapper#1]
It would be very, very nice to do `get_contexts(is_recursive=False)` which disables https://github.com/lfparis/forge-python-wrapper/blob/master/forge/forge.py#L649

Otherwise, running get_contents is too expensive on large projects.

**Comment by lfparis** [comment]
Resolved in latest release [0.0.1b4](https://pypi.org/project/forge-python-wrapper/0.0.1b4/)
